name: Deploy Hidrate.se

on:
  push:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Enviar arquivos via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/html"
          strip_components: 0
          overwrite: true